# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Lingua-Translate
version:      0.01
version_from: lib/POE/Component/Lingua/Translate.pm
installdirs:  site
license:      perl
requires:
    Lingua::Translate:             0.08
    POE:                           0
    POE::Component::Generic:       0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
